matrix:
  include:

    - language: bash
      sudo: required
      addons:
      apt:
        sources:
          - debian-sid
        packages:
          - shellcheck
      script:
        - project-fortis-backup/travis/ci.sh
      services:
        - docker
      after_success:
        - project-fortis-backup/travis/publish.sh
      env:
        NAME=project-fortis-backup

    - language: node_js
      node_js:
        - "6"
      cache:
        directories:
          project-fortis-interfaces/node_modules
      script:
        project-fortis-interfaces/travis/ci.sh
      env:
        NAME=project-fortis-interfaces

    - language: bash
      addons:
      apt:
        sources:
          - debian-sid
        packages:
          - shellcheck
      script:
        - project-fortis-pipeline/travis/ci.sh
      env:
        NAME=project-fortis-pipeline

    - language: node_js
      sudo: required
      node_js:
        - "9"
      cache:
        directories:
          project-fortis-services/node_modules
      script:
        project-fortis-services/travis/ci.sh
      services:
        - docker
      after_success:
        - project-fortis-services/travis/publish.sh
      env:
        NAME=project-fortis-services

    - language: scala
      jdk: oraclejdk8
      scala: 2.11.7
      dist: trusty
      sudo: required
      script:
        - project-fortis-spark/travis/ci.sh
      after_success:
        - project-fortis-spark/travis/publish.sh
      env:
        NAME=project-fortis-spark
