# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: master
  Image: "erikschlegel/spark-master"
  ImageTag: "2.2"
  Component: "spark-master"
  ImagePullPolicy: "Always"
  ServicePort: 7077
  ContainerPort: 7077
  #SparkSubmitCommand: ["spark-submit", "--master local[2]", "--driver-memory 4g", "enter-your-fat.jar"]
  #ConfigMapName: spark-master-conf
  Resources:
    Requests:
      Cpu: "700m"
      Memory: "3Gi"
    Limits:
      Cpu: "700m"
      Memory: "3Gi"
  # Set Master JVM memory. Default 1g
  DaemonMemory: 1g

WebUi:
  Name: webui
  ServicePort: 8080
  Component: "spark-webui"
  ProxyPort: 80
  ContainerPort: 8080
  Image: "elsonrodriguez/spark-ui-proxy:1.0"

Worker:
  Name: worker
  Image: "erikschlegel/spark-worker"
  ImageTag: "2.2"
  ImagePullPolicy: "Always"
  VmInstanceType: "Standard_L4s"
  Replicas: 6
  Component: "spark-worker"
  WorkingDirectory: "/opt/spark/work"
  ContainerPort: 8081
  #ConfigMapName: spark-master-conf
  Resources:
    Requests:
      Cpu: "700m"
      Memory: "3Gi"
    Limits:
      Cpu: "700m"
      Memory: "3Gi"
  Environment:
  - name: SPARK_DAEMON_MEMORY
    value: 1g
  - name: SPARK_WORKER_MEMORY
    value: 1g

Zeppelin:
  Name: zeppelin
  Image: "srfrnk/zeppelin"
  ImageTag: "0.7.0"
  Component: "zeppelin"
  Cpu: "100m"
  ServicePort: 8080
  ContainerPort: 8080

Persistence:
  # PvcAcctName: Secret
  # PvcPwd: Secret
  CheckpointDirectory: "/opt/checkpoint"
  #CheckpointShare: "checkpoint"